spring:
  config:
    import:
      - optional:file:env/spring.env[.properties]
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 6000ms

api:
  service-key: ${API_AIRPORT_PARKING_KEY}
  parking-base-url: http://openapi.airport.co.kr/service/rest/AirportParkingCongestion/airportParkingCongestionRT
  congestion-base-url: https://api.odcloud.kr/api/getAPRTPsgrCongestion_v2/v1/aprtPsgrCongestion%E2%80%8BV2
  apron-base-url: http://openapi.airport.co.kr/service/rest/FlightApronStateList/getFlightApronStatusList

logging:
  level:
    org.springframework.web.reactive.function.client: DEBUG
