spring:
  config:
    import:
      - optional:file:env/spring.env[.properties]

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 6000ms

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  api:
    service-key: ${API_AIRPORT_PARKING_KEY}
    parking-base-url: http://openapi.airport.co.kr/service/rest/AirportParkingCongestion/airportParkingCongestionRT
    congestion-base-url: https://api.odcloud.kr/api/getAPRTPsgrCongestion_v2/v1/aprtPsgrCongestion%E2%80%8BV2
    apron-base-url: http://openapi.airport.co.kr/service/rest/FlightApronStateList/getFlightApronStatusList

  logging:
    level:
      org.springframework.web.reactive.function.client: DEBUG
